name: Set up local EaaS instance
inputs:
  isBackend:
    description: "Defines whether the action was started from the UI or the Backend"
    required: false
    default: false
  branch:
    description: "Target branch for test execution. The artifacts from these branches will be set up by the local installer"
    required: true


runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v3
  - name: Set branch env var
    run: echo "OTHER_REPO_BRANCH=$(bash $GITHUB_ACTION_PATH/branches.sh ${{inputs.isBackend}} ${{inputs.branch}} )" >> $GITHUB_ENV
    shell: bash
  - name: Test if var was set properly
    run: echo "Branch that will be used for the other repository $OTHER_REPO_BRANCH"
    shell: bash

    # TODO
# run Python script to insert branches into config (use yaml)
# use provided branch for repo (UI if !isBackend, Server if isBackend)
# and OTHER_REPO_BRANCH for other repo

  - uses: actions/checkout@v3
  - uses: actions/setup-node@v3
    with:
      node-version: 18
  - name: Setup Test Server
    run: |
      (
      git clone https://eaas.dev/eaas-local-installer
      cd eaas-local-installer
      # HACK: using port 8080 is broken in eaas.dev/eaas-ansible
      sed -i "s/port: 8080/port: 80/" config/eaasi.yaml.template
      # HACK: scripts/install-dependencies.sh conflicts with packages preinstalled in GitHub Actions image
      sudo apt remove -y moby-containerd moby-runc
      cd ..
      sudo eaas-local-installer/scripts/install-test-server.sh || :
      )
    shell: bash
  - name: Wait for server to be ready
    run: while ! curl -f http://localhost/emil/Emil/buildInfo; do sleep 10; done
    shell: bash
  - name: Confirm Server is Ready
    run: echo "Server is Ready!"
    shell: bash


