name: Set up local EaaS instance
description: "Sets up a local EaaS instance (for testing)"

runs:
  using: "composite"
  steps:
  - name: ls test
    run: ls -la
    shell: bash
  - uses: actions/setup-node@v3
    with:
      node-version: 18
  - uses: actions/checkout@v3
    with:
      repository: emulation-as-a-service/eaas-installer
      ref: github-actions
      path: ./eaas-installer
  - name: Setup Test Server
    run: |
      # HACK: using port 8080 is broken in eaas.dev/eaas-ansible - TODO move to python script
      sed -i "s/port: 8080/port: 80/" eaas-installer/config/eaasi.yaml.template
      # HACK: scripts/install-dependencies.sh conflicts with packages preinstalled in GitHub Actions image
      sudo apt remove -y moby-containerd moby-runc
      sudo eaas-installer/scripts/install-test-server.py || :
    shell: bash
  - name: Wait for server to be ready
    run: while ! curl -f http://localhost/emil/admin/build-info; do sleep 10; done
    shell: bash
  - name: Confirm Server is Ready
    run: echo "Server is Ready!"
    shell: bash


