name: Set up local EaaS instance
description: "Sets up a local EaaS instance (for testing)"

runs:
  using: "composite"
  steps:
  - name: Setup Test Server
    shell: bash
    run: |
      # HACK: scripts/install-dependencies.sh conflicts with packages preinstalled in GitHub Actions image
      sudo apt remove -y moby-containerd moby-runc
      sudo -E "$GITHUB_ACTION_PATH/scripts/install-test-server.py"
    env:
      show_summary: true
