name: Installation test

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 00 00 * * *

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run installer action
        uses: ./
        env:
          import_test_environments: true
    timeout-minutes: 45
